### ISSUE TITLE
Clothes through texture on top of skeleton or a rigged model

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/threeAR-pose#10]
Overlaying a t-shirt or something should allow the user to move their hands and that part of the model should follow. Either build a skeleton model, map it on your body then put clothing texture on it. Or just grab a rigged model (one that has joint points).

Experiment with both, no need to implement yet.

**Comment by nawalmunif** [comment]
The approach of rigged model has following two important points to consider:

1. The 3D model should be rigged (this can be verified using any 3D creation suite, eg: Blender) and the Armature's bones should be labelled properly as they'll be addressed later.
2. The array of bones when the 3D model is loaded,  is accessed through its label. A particular parent/child node is associated with each bone having a unique number. 


The array of bones can be access via a global variable assigned to gltf inside the function. 
![image](https://user-images.githubusercontent.com/38717064/116302731-fae50200-a7ba-11eb-876f-a354cbbc7e8d.png)
//Here alien is the global variable

//Bones associated with a name and unique index
![image](https://user-images.githubusercontent.com/38717064/116302961-3d0e4380-a7bb-11eb-9882-c83df2fef48d.png)


A particular bone of the 3D model should be mapped to the posenet part.
For eg:
const boneLinkMap = {
      'mixamorig:RightShoulder' : getPart("rightShoulder", poses[0].pose)[0], 
      'mixamorig:LeftShoulder' : getPart("leftShoulder", poses[0].pose)[0],
    };
 //Bone names as accessible via array in the console : posenet model part

**Comment by nawalmunif** [comment]
The research part carried out brings to the conclusion that above approach (Rigged model and skeleton) would be best suitable at it less complex than grabbing the textures on the human model and mapping them. 

As far as the implementation of this approach is concerned, after mapping the Armature's bones to posenet model's parts, the 3D model should be adjusted as hands, arms or any other body part (as seen from the camera) moves.
