### ISSUE TITLE
Mask does not fit the face points properly

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/threeAR-pose#3]
Before https://github.com/dydx-git/threeAR-pose/commit/f439ed257a97a9d60013272c7de65735d7e47d4e flipped the stream horizontally, the mask would follow the x-axis correctly. Right now, it goes opposite. However, it always stayed above the y coordinates. Need a way to make the mask fit perfectly on a straight looking face

**Comment by nawalmunif** [comment]
Just had to play around y coordinate of mesh. 
To adjust particularly on face "meshPosition.y = -(nose.position.y / window.innerHeight) * 2 - 1;" 
-1 was added
