### ISSUE TITLE
Incomplete horizontal flip

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/threeAR-pose#4]
Commit https://github.com/dydx-git/threeAR-pose/commit/e2e6a5271feb829d9f969f78a9cf4307f255a3a2 flipped the canvas context but didn't flip the actual stream causing the webcam view to be flipped to what the posenet is fed as input. 

Anyways, **make the mask follow the face x-axis correctly.**

**Comment by Usmaneeyy** [comment]
The reason i didn't do that in the first place cause it is not a supported function by some browsers but i'll do it anyway now. Although if we are only giving the cords _from_ the canvas then whats the point of flipping the stream?

**Comment by dydx-git** [comment]
No, I'm not asking you to revert the flip. I'm sure there was a reason. Just make the mask follow the x coords correctly.

**Comment by Usmaneeyy** [comment]
Horizontal Flip is fixed now. 
Closing issue
