### ISSUE TITLE
Replace perspective camera with orthographic camera

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/threeAR-pose#8]
Replace perspective camera with orthographic camera such that the final view remains the same as it is now. In my experience, orthographic cameras tend to be at a position that makes the model a bit small so might need to either scale the model up or zoom the scene.

**Comment by Usmaneeyy** [comment]
⚡ Replaced perspective camera with orthographic camera
🐛 X-Y movement not working with orthographic camera at the moment due to some problems in pivot movement.

Closing issue.
